### ISSUE TITLE
ux: unable to exit config editor on inbrowser.tld

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#289] opened 2024-06-10 13:28 UTC
## Problem

If I open https://inbrowser.dev and click on  config editor:

> ![2024-06-10_15-25](https://github.com/ipfs/service-worker-gateway/assets/157609/b7009a56-b55e-46c5-a54e-eb2ad9f1c10a)

There is no way to close editor and go back to the main screen where i can enter the content path, i am stuck in config editor and have to manually edit URL in address bar:

> ![2024-06-10_15-22](https://github.com/ipfs/service-worker-gateway/assets/157609/2b54d4f7-6a73-49b2-bcca-6da1708eabc2)

## Fix ideas

- make clickin "Save config" collapse config when embedded on Iframe and remove `/#/ipfs-sw-config` from URL if not in iframe (on main domain)
- Or keep "Save Config" as-is and add dedicated "Close" button that does the above.

**Comment by SgtPooki** [comment] 2024-06-12 22:01
> make clicking "Save config" collapse config when embedded on Iframe and remove /#/ipfs-sw-config from URL if not in iframe (on main domain)

this is supposed to already exist. Will look into this now.

**Comment by SgtPooki** [comment] 2024-06-12 22:17
~~"save config" does close config edit screen on inbrowser.dev and local.~~ 

Actually, after clicking "reset config" it doesn't... interesting.

**Comment by SgtPooki** [comment] 2024-06-13 15:48
> Actually, after clicking "reset config" it doesn't... interesting.

After clearing all storage in the browser, and having a valid config, the reload button works fine, I can't reproduce on inbrowser.dev when using the settings gear icon directly from the homepage, and clicking "save config" to close it.


clicking "reset config" and then "save config" also continues to work after I cleared browser settings

**Comment by SgtPooki** [comment] 2024-06-13 17:53
and now I can reproduce locally with the code from https://github.com/ipfs/service-worker-gateway/pull/293.... I need to figure out what is going on

**Comment by SgtPooki** [comment] 2024-12-02 16:38
This was fixed by https://github.com/ipfs/service-worker-gateway/commit/c83830714475a7a20d949d5bf9f74bf65c7e387d & the implementation of `await fetch('/#/ipfs-sw-config-reload')`

**Closed as completed by SgtPooki** 2024-12-02 16:38 UTC
