### ISSUE TITLE
Duplicate block requests 

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#104] opened 2024-03-12 16:38 UTC
Opening  https://vitalik-eth.ipns.inbrowser.link/ on empty cache and empty browser profile requests https://trustless-gateway.link/ipfs/QmNTP17BS7AEHn4TuiyKYtKq1StCMxxXRSt4gpiTdyuHRB?format=raw five times:

> ![2024-03-12_17-28](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/6d762d63-a295-45a6-97b7-748e0e3136b0)

To see it, remember to preserve log, as SW will 

> ![2024-03-12_17-30](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/356e1f47-9d52-40fb-adec-1a765fc0d5f3)

**Comment by SgtPooki** [comment] 2024-03-12 19:20
could this be due to the prefetch we do when config is reloaded? https://github.com/ipfs-shipyard/helia-service-worker-gateway/blob/089cacded5d0e74dce6548fa8484b973bbf15ebd/src/redirectPage.tsx#L35

When we implement caching (#73), no more duplicate requests should be sent

**Comment by SgtPooki** [comment] 2024-04-15 15:39
FYI I am still seeing this today, but we don't have the cache updates in fully yet

<img width="948" alt="image" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/017c491e-186a-4e0a-be0f-4cbfab511732">

**Comment by SgtPooki** [comment] 2024-04-17 17:27
FYI I think https://github.com/ipfs/helia/pull/483 & https://github.com/ipfs/helia-verified-fetch/pull/50 resolves this.

**Comment by 2color** [comment] 2024-04-18 11:41
I've been looking into this issue and wanted to point out that the CID in question: [`QmNTP17BS7AEHn4TuiyKYtKq1StCMxxXRSt4gpiTdyuHRB`](https://explore.ipld.io/#/explore/bafybeidnycldkehcy6xixzqg72vad6pitav4lk5np3ev6tr6titlkvfpvi) is the `css` unixfs directory in the root of Vitalik's website.

The problem is that the Service Worker intercepts 5 concurrent requests to load css (all under the `css` folder) files after loading the initial HTML:
```
helia:service-worker-gateway helia-sw: incoming request url: https://vitalik-eth.ipns.inbrowser.dev/css/common-vendor.b8ecfc406ac0b5f77a26.css: +8ms
sw.ts:151 helia:service-worker-gateway helia-sw: incoming request url: https://vitalik-eth.ipns.inbrowser.dev/css/fretboard.f32f2a8d5293869f0195.css: +1ms
sw.ts:151 helia:service-worker-gateway helia-sw: incoming request url: https://vitalik-eth.ipns.inbrowser.dev/css/pretty.0ae3265014f89d9850bf.css: +0ms
sw.ts:151 helia:service-worker-gateway helia-sw: incoming request url: https://vitalik-eth.ipns.inbrowser.dev/css/pretty-vendor.83ac49e057c3eac4fce3.css: +0ms
sw.ts:151 helia:service-worker-gateway helia-sw: incoming request url: https://vitalik-eth.ipns.inbrowser.dev/css/global.css: +1ms
sw.ts:151 helia:service-worker-gateway helia-sw: incoming request url: https://vitalik-eth.ipns.inbrowser.dev/css/misc.css: +0ms
```

Because these are all handled concurrently when the block isn't retrieved and cached yet in the memory block store, the block is requested multiple times.

> FYI I think [ipfs/helia#483](https://github.com/ipfs/helia/pull/483) 

@SgtPooki Are you referring to any specific PR from that release?

> & [ipfs/helia-verified-fetch#50](https://github.com/ipfs/helia-verified-fetch/pull/50) resolves this.

My understanding is that sessions as implemented by [ipfs/helia-verified-fetch#50](https://github.com/ipfs/helia-verified-fetch/pull/50) scope related requests to a specific set of block brokers. Having said that, I don't see how that would solve this problem where essentially 5 requests from the same root CID that share the path segment `css` are made concurrently with Verified Fetch. 

I may be wrong, though.

**Comment by SgtPooki** [comment] 2024-04-18 12:23
There is some logic in helia sessions that append requests to inflight sessions based on root CID. 

My thought is that vfetch is kicking off multiple requests for the root because multiple subresources that need loaded (like you mention), and the session code would handle new "wants" by appending to inflight "want-sessions"

**Comment by SgtPooki** [comment] 2024-04-18 12:25
It is worth mentioning that even without sessions we should have a way to handle duplicate block requests though.

**Comment by 2color** [comment] 2024-04-18 13:16
> My thought is that vfetch is kicking off multiple requests for the root because multiple subresources that need loaded (like you mention), and the session code would handle new "wants" by appending to inflight "want-sessions"

This may be the case for the Bitswap BlockBroker, but for the default Verified Fetch which uses `helia/http`, I couldn't find [any logic that would handle this](https://github.com/ipfs/helia/blob/main/packages/block-brokers/src/trustless-gateway/broker.ts). 

> It is worth mentioning that even without sessions we should have a way to handle duplicate block requests though.

I agree.

**Comment by SgtPooki** [comment] 2024-04-18 17:00
> This may be the case for the Bitswap BlockBroker, but for the default Verified Fetch which uses `helia/http`, I couldn't find [any logic that would handle this](https://github.com/ipfs/helia/blob/main/packages/block-brokers/src/trustless-gateway/broker.ts?rgh-link-date=2024-04-18T13%3A16%3A14Z).

I believe that logic lives in https://github.com/ipfs/helia-verified-fetch/pull/50 currently. but yes, we need something in trustless-gateay block broker that can determine whether to kick off a `getRawBlock` request or not. a `Set` of inflight requests mapped on root and gateway should work

**Comment by SgtPooki** [comment] 2024-04-18 23:28
https://github.com/ipfs/helia/pull/503 will fix this once it is approved, merged, and released.

**Comment by SgtPooki** [comment] 2024-04-22 15:49
we need to make sure we get the latest [block-brokers](https://github.com/ipfs/helia/releases/tag/block-brokers-v2.1.1) into helia-verified-fetch, and then pull that in here before this is resolved

**Closed as completed** 2024-04-22 17:14 UTC
