### ISSUE TITLE
The cid: QmUkVeogWiPgxjVPTdw1Z6g3r9d2CFRCP75xXBp9sdwCnG the resources could not get out

### ISSUE THREAD

**Issue by kkurag** [ipfs/service-worker-gateway#15] opened 2023-10-15 12:58 UTC
The cid: QmUkVeogWiPgxjVPTdw1Z6g3r9d2CFRCP75xXBp9sdwCnG the resources could not get out
It is available through kubo, but not through heliaFetch

**Comment by SgtPooki** [comment] 2023-10-26 07:01
this is most likely an issue with the content availability to transports enabled on the browser. Check https://pl-diagnose.on.fleek.co/ to see all the providers of the CID, and discuss.ipfs.tech for support.

FYI, this codebase is not yet using the latest helia library, which does trustless gateway fetch and should be more reliable for fetching content.

closing this as not a bug.

**Closed as not planned by SgtPooki** 2023-10-26 07:01 UTC
